### PR TITLE
Network usage indicator

### PR DESCRIPTION
**Pull request by yomeuh**
Hey, this pull request is about issues #222 and #223
It creates the two widgets in indicator to display up and down bandwith. But I did not add icons.
It allows also to select widgets visibilty in indicator from the Monitor HeaderBar.
It seems to work well on my laptop but it needs some tests...

### CODE REVIEW

**Comment by stsdc** [comment]
Hey! Thanks for this PR!

Strangely I have a problem with updating visibility cpu, ram, etc.
obraz

**Comment by stsdc** [comment]
Silly me, forgot to restart the Wingpanel 😅

Now it works!

**Comment by yomeuh** [comment]
I realized the two new widgets settings are not saved when ending the monitor.

**Comment by stsdc** [comment]
@yomeuh  You have to reopen PR, so I can merge it.

**Comment by stsdc** [comment]
> I realized the two new widgets settings are not saved when ending the monitor.

Can You create another PR to fix this?

**Comment by yomeuh** [comment]
Sorry, I don't have time for that right now.
I'll do it in the next week

**Comment by stsdc** [comment]
No problem, take Your time 😌️

**Pull request merged**
