### PR TITLE
Fix the app crashes by clicking the "End/Kill Process" buttons when no process is selected

### LINKED ISSUE #97: When no process selected "End process" action segment faults the app
Console output:

```
(com.github.stsdc.monitor:11812): Gtk-CRITICAL **: 11:49:50.526: gtk_tree_model_get_iter: assertion 'path != NULL' failed

(com.github.stsdc.monitor:11812): Gtk-CRITICAL **: 11:49:50.526: gtk_tree_model_sort_get_value: assertion 'VALID_ITER (iter, tree_model_sort)' failed

(com.github.stsdc.monitor:11812): GLib-GObject-WARNING **: 11:49:50.526: ../../../../gobject/gtype.c:4265: type id '0' is invalid

(com.github.stsdc.monitor:11812): GLib-GObject-WARNING **: 11:49:50.526: can't peek value table for type '<invalid>' which is not currently referenced
Violación de segmento
```

_Violación de segmento_ ->  seg. fault :)

### PR DESCRIPTION
**Pull request by ryonakano**
Fixes #97

## BEFORE

2019-05-29 13 37 27 の画面録画

The app crashes by clicking the "End/Kill Process" button when there's no search result.

2019-05-29 13 38 16 の画面録画

The app also crashes by clicking the "End/Kill process" button when no process is selected after clearing search text.

## AFTER

2019-05-29 13 33 08 の画面録画

The app no longer crashes by clicking the "End/Kill process" button when there's no search result.

2019-05-29 13 34 14 の画面録画

The app now selects the first row after clearing search text.

## ~~TODO~~

~~Although now the "End/Kill Process" button is insensitive if there's no search result, the color of it does not turn to the one it should be. Its color should change like this demo:~~

2019-05-24 22 14 53 の画面録画

~~I'm not sure why this does not work.~~ :thinking:

### CODE REVIEW

**Comment by ryonakano** [comment]
I think the issue that the color of "End process" button does not turn to the one it should be is due to elementary stylesheet. I filed a issue at https://github.com/elementary/stylesheet/issues/507

**Comment by stsdc** [comment]
Merged #98. This PR can be updated now.

**Comment by stsdc** [comment]
Any more changes to this PR?

**Comment by ryonakano** [comment]
No, it's ready to be reviewed. :)

**Comment by stsdc** [comment]
There is one test case that we missed:
Start Monitor -> nothing is selected -> Kill/End process -> 

    (com.github.stsdc.monitor:9234): GLib-GObject-WARNING **: 18:46:11.023: can't peek value table for type '<invalid>' which is not currently referenced
    [1]    9234 segmentation fault  com.github.stsdc.monitor

**Comment by ryonakano** [comment]
Hmm I can't reproduce that case, because in my system when I run Monitor it automatically selects the first row of the process lists whether I run from Application Menu, from the dock, or from Terminal. Could you provide more details like screencast?

**Comment by ryonakano** [comment]
Ah I can confirm it by enabling "Show an indicator" and "Start in background" options.

**Comment by ryonakano** [comment]
Should be good now. :)

**Pull request merged**
