### PR TITLE
Support different gpus

### PR DESCRIPTION
**Pull request by stsdc**
- [x] amdgpu
- [x] nvidia
- [ ] intel

### CODE REVIEW

**Comment by stsdc** [comment]
@camellan please check if it still runs for nVidia

**Comment by camellan** [comment]
string gpu_name = get_sessman ().renderer.down ();
In my case it is: "geforce gt 610/pcie/sse2"

**Comment by camellan** [comment]
"else if (gpu_name.contains ("geforce")) " causes an error:
** (com.github.stsdc.monitor:10671): CRITICAL **: 22:57:55.601: session_manager_get_renderer: assertion 'self != NULL' failed

(com.github.stsdc.monitor:10671): GLib-CRITICAL **: 22:57:55.601: g_strsplit: assertion 'string != NULL' failed
Segmentation fault

**Comment by camellan** [comment]
here replace "nvidia"  by "geforce"
https://github.com/stsdc/monitor/blob/a0d71e5f3a834d7878ed48401d0b67e7f27d2d5c/src/Resources/Resources.vala#L30
and https://pastebin.com/EDJiEvfr
Then everything works

**Comment by stsdc** [comment]
@camellan how about now?

**Comment by camellan** [comment]
> @camellan how about now?

I can only check in the evening.

**Comment by camellan** [comment]
Checked. Everything is fine.

**Pull request merged**
