### PR TITLE
Compatibility improvements

### PR DESCRIPTION
**Pull request by hannesschulze**
Hi, I've changed a few things to improve the compatibility with other systems:

* I added an option to disable wingpanel indicator support (`-Dno_wingpanel`) because many distros don't have a package for that
* A check if X11 is available - this caused the app to crash when trying to run it on a Wayland session

### CODE REVIEW

**Comment by stsdc** [comment]
Your code looks OK.
But I'm not sure I want to target other distros. I think Monitor's counterparts on these systems are better then Monitor. And without Wingpanel support it difinitely has no chances.
I don't want to complicate the code to deliver shrinked version of Monitor.

I'm wondering on which system are You using Monitor? And why are You preferring it against other, more mature system monitoring apps? 🤔

**Comment by hannesschulze** [comment]
> I'm wondering on which system are You using Monitor?

I just installed Pop!_OS yesterday and wanted to try some elementary apps - wingpanel isn't in the Ubuntu repos, and I just think that it should be possible to build Monitor without having wingpanel (wingpanel also requires libmutter-2-dev which isn't available on Ubuntu 19.04 anymore)

> And why are You preferring it against other, more mature system monitoring apps?

I just like the overall layout of Monitor, since it's simple and straight-forward, and it has a tree view - I don't really know of any other monitor apps that have one (xfce4-taskmanager, gnome-system-monitor and even Stacer only have a list afaik).

But I think at least the Wayland support could be useful since elementary might switch to it some time in the future (and also for the AUR package).

**Comment by stsdc** [comment]
If You will make Wayland support in separate PR, I'll accept it.

And this PR will remain open until I decide what to do.

**Comment by worldofpeace** [comment]
I believe the code path here for the wingpanel indicator is very small.
You can easily have this build configuration in your CI to make sure the conditional compilation continues to build. Another thing is, there's numerous distros that want to package "made for elementary" apps, which means you open yourself up to packagers patches. If this breaks they're likely familiar to fix it, it's just conditional compilation for a single switch.

**Comment by worldofpeace** [comment]
It's also confusing, you mention other distros in your README https://github.com/stsdc/monitor#other-oses.

**Comment by stsdc** [comment]
If someone prepares CI, so we can be sure that everything works, I will consider this PR.

**Comment by stsdc** [comment]
Unintentionally closed this PR by deleting `unstable` branch. If You're still interested in this improvement, please use `dev` branch. Unfortunately I'm unable to reopen a PR.

**Comment by hannesschulze** [comment]
No problem, I could apply the diff again and open another PR but I don't know Houston well enough to set up different build options – so this would most likely be stuck at this stage until somebody else wants to set up CI :D

**Comment by stsdc** [comment]
Maybe it is possible to use this fancy new Github CI? :thinking:

**Comment by hannesschulze** [comment]
Github Actions is pretty great imo. I'm already using it for a couple of my own projects, however this wouldn't be the same build process elementary uses. I’ve seen some projects using Github Actions with Houston but that would be the same problem as with Travis I think.

**Pull request closed without merging**
