### PR TITLE
Fix add_process_to_row loop & segfaults

### PR DESCRIPTION
**Pull request by stsdc**

### CODE REVIEW

**Comment by stsdc** [comment]
Look at this @ryonakano. Because it is working now and I don't know why.

**Comment by ryonakano** [comment]
@stsdc Wow, I was thinking exactly the same solution!! (but I don't know why neither so I didn't comment… :sweat:)

**Comment by stsdc** [comment]
LOL, switched back to unstable. And there are no loops nor segfaults. :upside_down_face:

**Comment by ryonakano** [comment]
> Did You run any `apt upgrade`? Maybe some packages changed?

Nope.

**Comment by stsdc** [comment]
So on desktop it happened two times and I can't reproduce this anymore. :man_shrugging:

**Pull request merged**
