### PR TITLE
Update german translation

### PR DESCRIPTION
**Pull request by J0Ar**
Ok i think i managed the update of my branch (\😅️/ first time) and also updated the german translations.
Feel free to criticize me! 🙈️

### CODE REVIEW

**Comment by J0Ar** [comment]
I didn't know that. But also i do not know where those come from. This GitHub thing is just to complex for newbies. Thanks for your help.

**Comment by ryonakano** [comment]
> But also i do not know where those come from.

These lines are automatically added when source strings are changed and translation files are updated by translation programs.

For example, suppose a developer want to make sure users really want to delete a file. He/she should code something like this:

```vala
var warning_label = new Gtk.Label (_("Do You Want to Remove This File?"));
```

In this situation the string "Do You Want to Remove This File?" is translatable and will be shown to users. (The meaning of `var` of `new` is not what we want to focus on here, so you don't have to understand other part of this cord.)

After many translators translated this string, suppose this developer come to need more accurate expression. He/she decided to change this string to:

```vala
var warning_label = new Gtk.Label (_("Are You Sure You Want to Remove the Selected File?"));
```

Now compare those two strings. They may express the same thing essentially, but they don't use exactly the same words. So translation programs (like gettext) often marks changed strings as "fuzzy" when they update translation strings to let translators know there are some changes to those strings.

And if string changes are a bit and an old string is similar to a new one, the old one remains in the `msgstr` lines. However, if string changes are rather big and an old string is not similar to a new one, the old one is moved to the bottom of the translation file and commented out (which means putting `#` at the beginning of the line as they'll be no longer used unless exactly the same string is used in the code again). So you can remove those gray lines if you want, or you can left them as they are.

I tried to explain easier and carefully, but I'm sorry if this is verbose or difficult to understand. If this explanation is not enough, please let me know. 😊

**Comment by ryonakano** [comment]
BTW are you using a text-editor to add/edit translations? You may know but I recommend to use a po-editor like [POEdit](https://poedit.net/), because it automatically remove `fuzzy` lines when translators edit that string, so that we don't have to be careful of removing them.

**Comment by stsdc** [comment]
Thank You for Your contribution!
As @ryonakano said, check out some po-editor, it will make translating much more enjoyable. :wink:

**Pull request merged**
