### PR TITLE
Use Git submodule to fix the CI

### PR DESCRIPTION
**Pull request by ryonakano**
## Changes Summary
- Use Gitsubmodule instead of Meson's wrap-git  
In #163 the CI fails with the "Automatic wrap-based subproject downloading is disabled" error, but according to [the Meson's source code](https://github.com/mesonbuild/meson/blob/1ba62c484d3d4d1f75d59b4d9481f39914ffbb56/mesonbuild/wrap/wrap.py#L203-L208), Git submodule is always accepted:
- deb-packaging: Do not run `override_dh_auto_test`, since this tries to run tests which need GUI on Houston (which is CUI), and [causes the CI fails](https://travis-ci.org/github/stsdc/monitor/builds/673311769#L3484-L3490).
- Update referred commit of live-chart (optional)

### CODE REVIEW

**Comment by ryonakano** [comment]
The CI now passes: https://travis-ci.org/github/stsdc/monitor

**Comment by stsdc** [comment]
I liked meson wrap file :cry: 
Do You think it makes sense to ask for the wrap files support in Houston CI?

**Comment by ryonakano** [comment]
Yes, sounds nice to me :+1:

**Comment by stsdc** [comment]
@ryonakano I broke Your PR :sob:

**Comment by stsdc** [comment]
Also, here is Houston issue regarding wrap files: https://github.com/elementary/houston/issues/779

**Pull request merged**
